### ISSUE TITLE
Build error on windows

### ISSUE THREAD

**Issue by nin-jin** [yazd/backtrace-d#4]
Make it compatible with windows or convert error to warning, please.

**Comment by yazd** [comment]
The idea was that the user would only import it on linux using `version(linux)`. I am open to making it use `pragma(msg, "...")` instead of the assert but is there a reason not to version it from user code?

And in regards to implementing this on Windows, I don't have a machine to test or develop. A pull request to implement it would be great though.

**Comment by nin-jin** [comment]
I simply add dependency to dub.sdl:
```
dependency "backtrace-d" version="*"
```
And catch this error:
```
Error: static assert  "backtrace only works in a Linux environment, the advanced backtrace won't be attached."
```

Where i can insert `version(linux)`?

**Comment by yazd** [comment]
dub automatically compiles all dependencies. Although there is a way to specify different dependencies depending on architecture, I've simply replaced the `static assert` with `pragma(msg, ...)` because it's easier for users.
The symbols provided by the library are also versioned out on non-linux systems. So users must version their usage.
If there is still difficulty in using the library, report it please.
The changes are in version v0.1.1 on dub.

**Comment by nin-jin** [comment]
Thank you :-) How about autoinstall when can?

**Comment by yazd** [comment]
Uhmm, I am not sure it is the best thing to do, especially that you can use this library to get the stack trace without installing the printer.
I will close this issue because it is about the Windows thing. If you want to discuss the auto-install feature, please open another issue.
